name: artifacts-upload&download
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu@latest
    steps:
      - name: create-artifacts
        run: |
          mkdir af1
          echo "cfreating artifact in folder af1" > af1/artifact-file.txt

      - name: upload-artifacts
        uses: actions/upload-artifact@v7 # gave wrong action name
        with: 
          name: build-job-artifacts
          path: af1/
  
  deploy:
    runs-on: ubuntu@latest
    needs: build # make mistake here, i had to use needs: build instead of needs: build-job => this is because the job name is build, so we need to use the job name instead of the upload name
    steps:
      - name: download-artifacts
        uses: actions/download-artifact@v7
        with:
          name: build-job-artifacts # Must match the upload name exactly
          path: af1/ # Where to extract it        

      - name: modifying-artifacts
        run: |
          echo "modify artifact in folder af1" >> af1/artifact-file.txt

      - name: upload-artifacts-from-deplyjob
        uses: actions/upload-artifact@v7
        with: 
          name: deploy-job-artifacts
          path: af1/          
