name: artfact-test
on:
  workflow_dispatch:

jobs:
  create-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: import data from github repo
        uses: actions/checkout@v7

      - name: create more artifacts files
        run: |
          mkdir artifactDir
          echo "adding text to artfact-file1.md on date: $date" > artifactDir/artfact-file1.md
          pwd
      
      - name: upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: created-artifacts
          path: artifactDir/


    
